name: Build & Tests
on: push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '17'
            cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test
      - name: Lint
        run: yarn lint