name: Release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '17'
            cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test
      - name: Lint
        run: yarn lint 
      - name: Git config
        uses: BatchLabs/action.git-config@v1
      # TODO npm deploy
      - name: Documentation
        run: yarn doc:deploy